### ISSUE TITLE
Sometimes when jumping the anticheat detects you teleporting.

### ISSUE THREAD

**Issue by ccuser44** [Hexcede/Hexolus-OpenSource#5]
The 1.2 stud teleport limit sometimes detects false detections.. I think it should be increased to 5.5 or something.

**Comment by ccuser44** [comment]
Also the teleport detection gets fired too easily.
Like sometimes it false detects you for teleporting 2.3 studs or even less which isn't a lot.

**Comment by Hexcede** [comment]
Yep, this is an issue I am concerned with. Ideally false detections should never happen however its fairly difficult to prevent due to Roblox's physics being a little quirky. The anticheat predicts where the player should be and corrects their position and velocity if it goes outside of the predicted range. This causes a minor "rubber banding" effect since the change happens about 2 or 3 frames late on the client so its a little out of sync for them, but, for other players its completely seamless.

I would like to partially solve this behaviour by allowing some components of the anticheat to run on the client as well as the server, which would act as a filter. This would not take too much effort for me to implement since the anticheat is for the most part designed to behave as expected regardless of where its running. This still wouldn't fix most false positives, it would only make the physics much more consistent between the client and server.

I would really not like to increase the threshold so long as it doesn't cause major issues in games, as, the lower the threshold can be, the better, but, in the long run this threshold likely will still be increased as there is no possible way to completely perfect the prediction due to varying network speeds and such.

1.2 studs vs even 2 studs creates a pretty big difference even if the same false positives occur, since, the discrepancy is reduced. If someone fails a movement check, they are moved to the predicted position which includes the extra threshold. The downside is, 1.2 studs vs 2 studs still creates a pretty noticeable difference in how fast an exploiter can move if they use teleportation, unfortunately.

**Comment by Hexcede** [comment]
Thresholds have been adjusted for now. Let me know if this issue is still occurring frequently enough to cause issues.
